
package hrms.ws.client.qms.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HrmsOcupationVacationHttpPost", targetNamespace = "http://tempuri.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HrmsOcupationVacationHttpPost {


    /**
     * 
     * @param endDate
     * @param action
     * @param startDate
     */
    @WebMethod(operationName = "GetOcupationDetails")
    public void getOcupationDetails(
        @WebParam(name = "action", partName = "action")
        String action,
        @WebParam(name = "startDate", partName = "startDate")
        String startDate,
        @WebParam(name = "endDate", partName = "endDate")
        String endDate);

}
