
package hrms.ws.client.qms.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HrmsOcupationVacationSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HrmsOcupationVacationSoap {


    /**
     * 
     * @param endDate
     * @param action
     * @param startDate
     * @return
     *     returns GetOcupationDetailsResponse.GetOcupationDetailsResult
     */
    @WebMethod(operationName = "GetOcupationDetails", action = "http://tempuri.org/GetOcupationDetails")
    @WebResult(name = "GetOcupationDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOcupationDetails", targetNamespace = "http://tempuri.org/", className = "javaapplication1.GetOcupationDetails")
    @ResponseWrapper(localName = "GetOcupationDetailsResponse", targetNamespace = "http://tempuri.org/", className = "javaapplication1.GetOcupationDetailsResponse")
    public GetOcupationDetailsResponse.GetOcupationDetailsResult getOcupationDetails(
        @WebParam(name = "action", targetNamespace = "http://tempuri.org/")
        String action,
        @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate);

}
