
package hrms.ws.client.qms.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HrmsOcupationVacation", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://equarters.nic.in/HrmsOcupationVacation.asmx?wsdl")
public class HrmsOcupationVacation
    extends Service
{

    private final static URL HRMSOCUPATIONVACATION_WSDL_LOCATION;
    private final static WebServiceException HRMSOCUPATIONVACATION_EXCEPTION;
    private final static QName HRMSOCUPATIONVACATION_QNAME = new QName("http://tempuri.org/", "HrmsOcupationVacation");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://equarters.nic.in/HrmsOcupationVacation.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HRMSOCUPATIONVACATION_WSDL_LOCATION = url;
        HRMSOCUPATIONVACATION_EXCEPTION = e;
    }

    public HrmsOcupationVacation() {
        super(__getWsdlLocation(), HRMSOCUPATIONVACATION_QNAME);
    }

    public HrmsOcupationVacation(WebServiceFeature... features) {
        super(__getWsdlLocation(), HRMSOCUPATIONVACATION_QNAME, features);
    }

    public HrmsOcupationVacation(URL wsdlLocation) {
        super(wsdlLocation, HRMSOCUPATIONVACATION_QNAME);
    }

    public HrmsOcupationVacation(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HRMSOCUPATIONVACATION_QNAME, features);
    }

    public HrmsOcupationVacation(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HrmsOcupationVacation(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HrmsOcupationVacationSoap
     */
    @WebEndpoint(name = "HrmsOcupationVacationSoap")
    public HrmsOcupationVacationSoap getHrmsOcupationVacationSoap() {
        return super.getPort(new QName("http://tempuri.org/", "HrmsOcupationVacationSoap"), HrmsOcupationVacationSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HrmsOcupationVacationSoap
     */
    @WebEndpoint(name = "HrmsOcupationVacationSoap")
    public HrmsOcupationVacationSoap getHrmsOcupationVacationSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "HrmsOcupationVacationSoap"), HrmsOcupationVacationSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns HrmsOcupationVacationSoap
     */
    @WebEndpoint(name = "HrmsOcupationVacationSoap12")
    public HrmsOcupationVacationSoap getHrmsOcupationVacationSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "HrmsOcupationVacationSoap12"), HrmsOcupationVacationSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HrmsOcupationVacationSoap
     */
    @WebEndpoint(name = "HrmsOcupationVacationSoap12")
    public HrmsOcupationVacationSoap getHrmsOcupationVacationSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "HrmsOcupationVacationSoap12"), HrmsOcupationVacationSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns HrmsOcupationVacationHttpGet
     */
    @WebEndpoint(name = "HrmsOcupationVacationHttpGet")
    public HrmsOcupationVacationHttpGet getHrmsOcupationVacationHttpGet() {
        return super.getPort(new QName("http://tempuri.org/", "HrmsOcupationVacationHttpGet"), HrmsOcupationVacationHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HrmsOcupationVacationHttpGet
     */
    @WebEndpoint(name = "HrmsOcupationVacationHttpGet")
    public HrmsOcupationVacationHttpGet getHrmsOcupationVacationHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "HrmsOcupationVacationHttpGet"), HrmsOcupationVacationHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns HrmsOcupationVacationHttpPost
     */
    @WebEndpoint(name = "HrmsOcupationVacationHttpPost")
    public HrmsOcupationVacationHttpPost getHrmsOcupationVacationHttpPost() {
        return super.getPort(new QName("http://tempuri.org/", "HrmsOcupationVacationHttpPost"), HrmsOcupationVacationHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HrmsOcupationVacationHttpPost
     */
    @WebEndpoint(name = "HrmsOcupationVacationHttpPost")
    public HrmsOcupationVacationHttpPost getHrmsOcupationVacationHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "HrmsOcupationVacationHttpPost"), HrmsOcupationVacationHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HRMSOCUPATIONVACATION_EXCEPTION!= null) {
            throw HRMSOCUPATIONVACATION_EXCEPTION;
        }
        return HRMSOCUPATIONVACATION_WSDL_LOCATION;
    }

}
